name: Doc Preview Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  doc-preview-cleanup:
    runs-on: self-hosted
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Delete preview and history + push changes (JSMO)
        run: |
            if [ -d "previews/PR$PRNUM" ]; then
              git config user.name "Documenter.jl"
              git config user.email "documenter@juliadocs.github.io"
              git rm -rf "previews/PR$PRNUM"
              git commit -m "delete preview"
              git branch gh-pages-new $(echo "delete history" | git commit-tree HEAD^{tree})
              git push --force origin gh-pages-new:gh-pages
            fi
        env:
            PRNUM: ${{ github.event.number }}
      - name: Checkout gh-pages-PumasQSP branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages-PumasQSP
      - name: Delete preview and history + push changes (PumasQSP)
        run: |
            if [ -d "previews/PR$PRNUM" ]; then
              git config user.name "Documenter.jl"
              git config user.email "documenter@juliadocs.github.io"
              git rm -rf "previews/PR$PRNUM"
              git commit -m "delete preview"
              git branch gh-pages-PumasQSP-new $(echo "delete history" | git commit-tree HEAD^{tree})
              git push --force origin gh-pages-PumasQSP-new:gh-pages-PumasQSP
            fi
        env:
            PRNUM: ${{ github.event.number }}