name: TagBot
on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
jobs:
  TagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'ChrisRackauckas'
    runs-on: self-hosted
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.JULIASIM_REGISTRY_SSH_KEY }}
          registry: JuliaComputing/JuliaSimRegistry
          registry_ssh: ${{ secrets.JULIASIM_REGISTRY_SSH_KEY }}
